### Application
application:
  name: "^project.artifactId^"
  version: "^project.version^"
  timestamp: "^timestamp^"


### Deployment
deployment:
  scheme: "http"
  hostname: "localhost"
  port: ${server.port}

### Server / API
server:
  port: 8081
  error:
    include-message: always

spring:
  application:
    name: SelfDescriptionService
  docker:
    compose:
      enabled: false


basyx:
  smrepo:
    name: sm-repo
  backend: InMemory


resource:
  aas-id: ""
  id: "asdf"

aas:
  submodel-repository:
    scheme: ${deployment.scheme}
    host: ${deployment.hostname}
    port: ${server.port}
    path:
    url: ${aas.submodel-repository.scheme}://${aas.submodel-repository.host}:${aas.submodel-repository.port}${aas.submodel-repository.path}

### Consul
consul:
  scheme: http
  host: c8.slm.loca
  port: 8500
  datacenter: fabos
  acl-token: 0h8W8Sp2VS4bIQUtHKHCtQvh