### Application
application:
  name: "^project.artifactId^"
  version: "^project.version^"
  timestamp: "^timestamp^"


### Deployment
deployment:
  scheme: "http"
  hostname: "localhost"
  port: ${server.port}

### Server / API
server:
  port: 8081
  error:
    include-message: always

spring:
  application:
    name: SelfDescriptionService
  docker:
    compose:
      enabled: false


basyx:
  smrepo:
    name: sm-repo
  backend: InMemory


resource:
  id: "asdf"

aas:
  broker:
    host: localhost
    port: 1884
  aas-registry:
    scheme: http
    host: localhost
    port: 8082
    path:
    url: ${aas.aas-registry.scheme}://${aas.aas-registry.host}:${aas.aas-registry.port}${aas.aas-registry.path}
  aas-repository:
    scheme: http
    host: localhost
    port: 8081
    path:
    url: ${aas.aas-repository.scheme}://${aas.aas-repository.host}:${aas.aas-repository.port}${aas.aas-repository.path}
  submodel-registry:
    scheme: http
    host: localhost
    port: 8083
    path:
    url: ${aas.submodel-registry.scheme}://${aas.submodel-registry.host}:${aas.submodel-registry.port}${aas.submodel-registry.path}
  submodel-repository:
    scheme: http
    host: localhost
    port: 8081
    path:
    url: ${aas.submodel-repository.scheme}://${aas.submodel-repository.host}:${aas.submodel-repository.port}${aas.submodel-repository.path}
  concept-descriptions-repository:
    scheme: http
    host: localhost
    port: 8081
    path:
    url: ${aas.concept-descriptions-repository.scheme}://${aas.concept-descriptions-repository.host}:${aas.concept-descriptions-repository.port}${aas.concept-descriptions-repository.path}

### Consul
consul:
  scheme: http
  host: fabos.local
  port: 8500
  datacenter: fabos
  acl-token: 2HUzRANRCFAcsqfwrASWJiPX