name: Build Snapshot Release

permissions:
  contents: write

on:
  push:
    tags:
      - "*"
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      MAVEN_CLI_OPTS: "-T 8 --batch-mode --errors --fail-at-end --show-version --no-transfer-progress -DinstallAtEnd=true -DdeployAtEnd=true"
      MAVEN_PROFILES: ""

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 19
        uses: actions/setup-java@v4
        with:
          java-version: '19'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn $MAVEN_PROFILES $MAVEN_CLI_OPTS package
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Log test output on failure
        if: failure() || cancelled()
        run: find . -type f -path "*test-reports/*-output.txt" -exec tail -n +1 {} +

      - name: Get Version
        run: echo "VERSION=$(echo $(mvn help:evaluate -Dexpression=project.version -q -DforceStdout))" >> $GITHUB_ENV

      - name: Set Name
        if: github.ref_name == 'develop'
        run: echo "NAME=$(echo resource-self-description-service-develop-${{env.VERSION}})" >> $GITHUB_ENV

      - name: Set Name
        if: github.ref_name == 'main' || github.ref_type == 'tag'
        run: echo "NAME=$(echo resource-self-description-service-${{env.VERSION}})" >> $GITHUB_ENV

      - name: Copy Jar exec
        run: cp service/service.rest/target/*-exec.jar ${{env.NAME}}.jar

      - name: Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          draft: true
          prerelease: true
          tag_name: ${{env.NAME}}
          name: ${{env.NAME}}
          files: ${{env.NAME}}.jar
